import { dirname, join } from 'node:path';
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

const scriptDir = dirname(fileURLToPath(import.meta.url));
const hubRoot = join(scriptDir, '..');
const outputPath = join(hubRoot, 'src', 'web', 'embeddedAssets.generated.ts');
const contents = [
    '// This file is generated by hub/scripts/write-embedded-assets-stub.ts for standalone hub builds.',
    '// It intentionally contains no embedded assets.',
    '',
    'export interface EmbeddedWebAsset {',
    '    path: string;',
    '    sourcePath: string;',
    '    mimeType: string;',
    '}',
    '',
    'export const embeddedAssets: EmbeddedWebAsset[] = [];',
    ''
].join('\n');

writeFileSync(outputPath, contents, 'utf-8');
